"""Rename column argument

Revision ID: 61e1fad1fa98
Revises: 
Create Date: 2021-07-25 21:28:06.868348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e1fad1fa98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_index(op.f('ix_admin_user_name'), 'admin_user', ['name'], unique=True)
    op.create_table('bean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bean_country'), 'bean', ['country'], unique=False)
    op.create_index(op.f('ix_bean_name'), 'bean', ['name'], unique=False)
    op.create_index(op.f('ix_bean_rating'), 'bean', ['rating'], unique=False)
    op.create_index(op.f('ix_bean_region'), 'bean', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bean_region'), table_name='bean')
    op.drop_index(op.f('ix_bean_rating'), table_name='bean')
    op.drop_index(op.f('ix_bean_name'), table_name='bean')
    op.drop_index(op.f('ix_bean_country'), table_name='bean')
    op.drop_table('bean')
    op.drop_index(op.f('ix_admin_user_name'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
